const subcategories = {
  Technology: [
    'AI',
    'Web Development',
    'Mobile Apps',
    'Cloud Computing',
    'Cybersecurity',
    'IoT',
    'Blockchain',
    'Tech Reviews',
  ],
  Health: [
    'Fitness',
    'Nutrition',
    'Mental Health',
    'Medical Advances',
    'Preventive Care',
  ],
  Finance: [
    'Investing',
    'Cryptocurrency',
    'Personal Finance',
    'Banking',
    'Financial Planning',
    'Taxes',
  ],
  Travel: [
    'Destinations',
    'Travel Tips',
    'Adventure',
    'Budget Travel',
    'Cultural Experiences',
  ],
  Automotive: [
    'Electric Vehicles',
    'Car Reviews',
    'Car Maintenance',
    'Car Tech',
    'Motorsports',
  ],
  Insurance: [
    'Health Insurance',
    'Auto Insurance',
    'Life Insurance',
    'Home Insurance',
    'Business Insurance',
  ],
  Marketing: [
    'Digital Marketing',
    'SEO',
    'Content Strategy',
    'Social Media',
    'Email Marketing',
    'Branding',
  ],
  Programming: [
    'JavaScript',
    'Python',
    'Full-Stack Development',
    'Frameworks',
    'Open Source',
    'Coding Best Practices',
  ],
  'Artificial Intelligence': [
    'Machine Learning',
    'Natural Language Processing',
    'Computer Vision',
  ],
  Gaming: [
    'Game Reviews',
    'Game Development',
    'eSports',
    'Console Gaming',
    'PC Gaming',
    'Mobile Gaming',
  ],
  Education: [
    'Online Learning',
    'Study Tips',
    'EdTech',
    'Course Reviews',
    'Student Life',
    'Language Learning',
  ],
  Business: [
    'Entrepreneurship',
    'Startups',
    'Management',
    'Business Strategy',
    'Productivity',
    'HR',
  ],
  Science: [
    'Space',
    'Physics',
    'Biology',
    'Chemistry',
    'Research',
    'Science News',
  ],
  'Programming Languages': [
    'JavaScript',
    'Python',
    'Java',
    'C#',
    'C++',
    'Ruby',
    'PHP',
    'Swift',
    'Go',
    'Rust',
  ],
  'Web Development': [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
  ],
  'Mobile Development': [
    'iOS Development',
    'Android Development',
    'Flutter',
    'React Native',
  ],
  'Game Development': ['Unity', 'Unreal Engine', 'Game Design'],
  'Data Science': ['Data Analysis', 'Machine Learning', 'Deep Learning'],
  'Cloud Computing': ['AWS', 'Azure', 'Google Cloud'],
  Cybersecurity: ['Network Security', 'Application Security'],
  Blockchain: ['Cryptocurrency', 'Smart Contracts'],
  DevOps: ['CI/CD', 'Containerization', 'Microservices'],
  'Software Testing': [
    'Unit Testing',
    'Integration Testing',
    'Test Automation',
  ],
  'Internet of Things': ['IoT Architecture', 'IoT Security'],
  'Virtual Reality': ['VR Development', 'AR Development'],
  'Augmented Reality': ['AR Development', 'Mixed Reality'],
  'Game Design': ['Game Mechanics', 'Level Design'],
  'Game Programming': ['Game Engines', 'Scripting Languages'],
  'Game Art': ['3D Modeling', 'Texturing'],
  'Game Sound': ['Sound Design', 'Music Composition'],
  'Game Marketing': ['Game Promotion', 'Community Management'],
};
const categories = Object.keys(subcategories);
module.exports = {
  categories,
  subcategories,
};
